### ISSUE TITLE
How works with Tdarr

### ISSUE THREAD

**Issue by Sergiomg86** [Schaka/janitorr#34]
How does it work with Tdarr?

I'm surprised no one has written about this, but I'm wondering how an optimization program that converts h264 to h265 will work with software that deletes files.

I ask me if Janitorr would recognize it as a new item when I replace it with Tdarr, I understand the name is the same but the creation date is not.

Thank you

**Comment by Schaka** [comment]
No. I don't think that many people use Tdarr. 

Most people will just grab quality encodes by someone who put in considerable work. Otherwise you're keeping twice the content during seeding time anyway. And if you're using Usenet, why bother with tdarr when you can grab as much as you want?

Janitorr doesn't delete files directly. It tells Radarr/Sonarr which shows to delete based on grab history (and watch history - see JellyStat). If Radarr/Sonarr can delete the "new" file, it should work for you.

Just try it in dry-run mode.

I'm going to close this ticket because I won't support tdarr officially.

**Comment by Sergiomg86** [comment]
Nothing happens, I have it automated and sometimes it downloads h264 files because there is no h265 format

However, I confirm that it is compatible, sonarr and radarr make the change from file to fire without realizing it and without problem

**Comment by Schaka** [comment]
H265 isn't always better especially if you're automatically using some template encode settings to convert an h264 encode.

The quality will be ass.

Janitorr should still work for your use case. It doesn't care about the actual files, only the info it gets from the arrs history.
