### ISSUE TITLE
[Question] How does Janitorr work with Jellystat?

### ISSUE THREAD

**Issue by nothing2obvi** [Schaka/janitorr#43]
Sorry, I know it's not a bug but I don't know where to ask a question. I've been using dry run this whole time because I'm still confused about how this all works.

If I use tag-based deletion for 30 days, and the last episode of the season was 30 days ago, but an episode from the season was watched 25 days ago as evidenced on Jellystat, is the season still marked for deletion or is a countdown to deletion reset?

I guess I'd like to know:
1.) When a season is marked for deletion (e.g. with a 30d tag)
2.) How many days until that season is deleted (Is it 14d after the 30d has passed since the last episode? 14d is my leaving soon setting. Or is it simply 30d since the last episode? In which case, does it enter leaving soon on day 16?)
3.) What happens if someone watches an episode from that season within that time period in point 2 -- Is the countdown timer to deletion reset?

Thanks!

**Comment by Schaka** [comment]
I guess I need to clear up a few things.

There is no timer. Janitorr runs every hour to do calculations.
Everything that fits into your Leaving Soon (today - 14d) time window, will be treated as such.

Everything that fits into the deletion window (today - 30d and OLDER) will get deleted.

Now initially, the age is determined by when things were grabbed in Sonarr. If the season was watched (obtained via Jellystat), the date used to calculate the age is overwritten by the most recent watch (rather than most recent grab).

So using Jellystat you're essentially replacing the age calculation via watch history.

Does that answer your question? I felt like just answering your questions directly made little sense, but for clarity's sake:

1. When it was grabbed 30 days ago or watched 30 days ago and not since
2. Leaving Soon is calculated separately, so whatever deletion date you set (30d, maybe?)
3. Yes it gets reset, the date is always from last watched

**Comment by nothing2obvi** [comment]
Hi, thank you, yes, that definitely clears some things up for me. I think the thing I'm stuck on is the Leaving Soon classification.

So if my leaving soon parameter is 14d, and my tag is for 30d, and the last episode of the season was grabbed/watched on July 1st:
- On what day does the season enter Leaving Soon on Jellyfin? (Is it July 17th?)
- On what day does the season get deleted? (Is it July 31st?)

And just to clarify my understanding, if the last episode of the season was grabbed on July 1st, but an episode from the season was watched on July 15th, is the new date for deletion August 14th?

Thanks again. I want to use Janitorr, I'm just want to make sure I understand everything before I disable dry run.

**Comment by Schaka** [comment]
I think the config file explains that pretty well.
The 14d leaving soon Window is an offset from deletion date.

If you set a season to be deleted after 30 days, then after 16 days - 14 days before it is due for deletion (30-14) it would appear in the leaving soon collection.

Then if nobody watches it for the next 14 days, it will be deleted.

If somebody watches it, the date is now today and 16 days from today, it will appear in the leaving soon collection again.

Whether things will be removed from deleting soon will be determined by whether you clean the directory. Entries will only be removed when using the from scratch option or if they're deleted from the library.

FYI the last grab isn't determined by whichever is the latest episode and when it was downloaded. It's determined by whichever episode was downloaded by the latest date in the given season

**Comment by nothing2obvi** [comment]
This answers my questions. Thank you. I can now start using Janitorr.
