### ISSUE TITLE
application failed to start

### ISSUE THREAD

**Issue by rickardfransson** [Schaka/janitorr#64]
Need som help here. Tried almost everything..
This is what comes up after starting container and running logs
https://pastebin.com/kYvkuEHc

This is my config:
https://pastebin.com/Np99Bvwz

And this is my docker-compose. Path to application.yml is a folder that sits next no docker-compose. (In the same folder)
https://pastebin.com/AX9NN6CA
![image](https://github.com/user-attachments/assets/98cd2f00-ac58-4bf1-9b01-ac0da91ea68c)

What have I done wrong or is my system to old?

**Comment by Schaka** [comment]
According to the error message, you did NOT map the application.yml into your container correctly.
You are mapping:
`/appdata/janitorr/config/application.yml:/workspace/application.yml`

But you're telling me your `application.yml` file is stored under `/opt/janitorr/config/application.yml`
So unless there is something you're not telling, your mapping needs to be:
`/opt/janitorr/config/application.yml:/workspace/application.yml`

If the `native-develop` image still does not work for your platform, use the `stable` image and map
`/opt/janitorr/config:/config`.

**Comment by rickardfransson** [comment]
This is with native and new mapping:
![image](https://github.com/user-attachments/assets/6b905cdf-d9d2-47f8-8354-5ee30c83271c)

And this is with stable image and the other mapping
![image](https://github.com/user-attachments/assets/eae32ba6-8ce6-4a52-9784-beb03dcfaf31)

**Comment by Schaka** [comment]
I am just now realizing you said the `application.yml` is next to your `docker-compose.yml`.
It's not showing in your screenshot then - why?

If that is still true, put it inisde the config folder and use the mappings [I gave here](https://github.com/Schaka/janitorr/issues/64#issuecomment-2353263761)

**Comment by rickardfransson** [comment]
Well, maybe I wasnt all clear there.. Trying some things here right now, but here is my full path:
/home/rickardfransson/opt/janitorr/config

I changed that in compose and got bunch of more faults :-(

**Comment by rickardfransson** [comment]
Moving forward or backward.. Really dont now. This is log now
https://pastebin.com/w627Baii

With this compose:
![image](https://github.com/user-attachments/assets/4cf5f1e1-241c-4b3e-9a3d-5f93a57e2610)

Linux isnt my strong side. 2 years practice in docker and still dont get it.....

**Comment by Schaka** [comment]
Put your `application.yml` inside this folder: `/home/rickardfransson/opt/janitorr/config`

Map either
- `/home/rickardfransson/opt/janitorr/config/application.yml:/workspace/application.yml` for native image
- `/home/rickardfransson/opt/janitorr/config:/config` for non-native

You're mapping your host folder to a specific folder inside the container. The folder inside the container is required and does not change. You literally only have to change how you point it towards the config file. It's the very basics of how Docker works.

The last error you posted is because it cannot connect to Sonarr. You can read the error message. That host/port combination does not allow a connection. 

If the containers are on the same system and the same Docker network, they are probably reachable to Janitorr as something like `http://sonarr:8989`. If they're publically accessible, it's probably something like https://sonarr.mydomain.com/ - but not what you used.

Janitorr works, the mapping is correct now. So I'm closing this ticket. 
If you run into any issues with Janitorr (i.e. real bug once it's running), feel free to open another ticket. However, the issue tracker is not for basic tech support.
