### ISSUE TITLE
Don't delete *arss entries

### ISSUE THREAD

**Issue by bonswouar** [Schaka/janitorr#76]
I've found the issue #29 that was somewhat close to my problem/question, but got sidetracked on Sonarr specifically and last season stuff etc, thus doesn't solve it

The point of the user was _"Sonarr entry is not media, its just some database lines"_, and I've got the same logic for **Sonarr & Radarr**: as they're just databases, mostly filled from auto Import List, deleting a database entry doesn't make any sense (in my case). It will loose all history, and will probably be re-added (and monitored!) sooner or later with those Import Lists....

**Is there any way to only delete the files, not the database entry?** That's what I usually do (and it gets automatically unmonitored when files are deleted) and it makes much more sense in my use case

**Comment by Schaka** [comment]
The whole point of Janitorr is deleting everything, including the history and requests, is so that if someone really wants to watch something again, they can go request it.

The point of Janitorr is there not being a trace. That's why it also deletes the folder via Jellyfin. If don't delete the entry in the arrs, you'll be left with orphaned folders too.

While it's technically possible to write a bunch of conditions and disable deletion altogether, I really don't think it belongs here.
I'm not even sure the arrs have an endpoint for just deleting the files but keeping the entry. Usually it's deleting the entry with the option of keeping the files.

**Comment by bonswouar** [comment]
> The whole point of Janitorr is deleting everything, including the history

I see, I thought the main point was to delete files to save space :/

>  and requests, is so that if someone really wants to watch something again, they can go request it.

With Jellyseerr, a deleted movie/show (files only) can already be requested again!

> The point of Janitorr is there not being a trace. That's why it also deletes the folder via Jellyfin. If don't delete the entry in the arrs, you'll be left with orphaned folders too.

I can be fine with orphaned files I guess, that's not what's taking most of the space... Not really an issue imo

> While it's technically possible to write a bunch of conditions and disable deletion altogether, I really don't think it belongs here.
I'm not even sure the arrs have an endpoint for just deleting the files but keeping the entry. Usually it's deleting the entry with the option of keeping the files.

Well I understand.. That's kinda disappointing as I'd have expected most people to use *arrs like me.
When you've got many Import Lists in Radarr you certainly don't want db entries to be deleted at any point, do you?!

If you've got any hint on how I should use those tools I'm open to suggestions though...
_(but in general - as an user, an admin sys, and a dev - deleting history, leaving "no trace", doesn't sound like a good thing to me)_

**Comment by Schaka** [comment]
> Well I understand, that's kinda disappointing as I'd have expected most people to use *arrs as I do..

I don't think they do. For starters, I don't know what lists you're talking of. I assume you auto import every popular movie and show based off of Trakt, letterboxd, etc?

Personally, I don't know anyone who uses it that way, but I'm not going to claim to have a relevant sample size. 

> (but in general - as an user, an admin sys, and a dev - deleting history, removing any trace, doesn't sound so great to me)

The arrs are just a representation and metadata manager for what's in your library of sorts. I don't think they should necessarily be responsible for keeping a history of whatever was there at one point, where you acquired it etc.

That being said, I did look into both Radarr and Sonarr and there's technically a way to access all files belonging to a movie, then delete those, keeping the database entry. 

What I've pushed now and what will be available in the latest develop image is an option to only do file cleanup but keep the database entry.

I've NOT disabled Jellyfin's cleanup, meaning Jellyfin may or may not delete all additional files and you may lose folders. But your *arr entries will not be touched.

Hopefully that's what you were looking for. If it turns out Jellyfin deletion needs to be disabled, I will probably refer users to the Jellyfin property so they can choose to disable it if they want.

**Comment by bonswouar** [comment]
> I don't think they do. For starters, I don't know what lists you're talking of. I assume you auto import every popular movie and show based off of Trakt, letterboxd, etc?
> Personally, I don't know anyone who uses it that way, but I'm not going to claim to have a relevant sample size.

I guess you're right, after talking with a couple of Radarr users it seems I'm kinda the only one using Import Lists :laughing: 
But for your information, yeah basically I auto import few Popular movies ; but mostly I import all future movies from actors/writers/directors that I follow! You can even add those Import List directly from the Movie's page on Radarr by clicking on a cast/crew

> What I've pushed now and what will be available in the latest develop image is an option to only do file cleanup but keep the database entry.

That sounds perfect! I wasn't so sure that was doable with your current architecture, glad you could make it work :)

I'll let you know if this works as expected, but from what you're saying that should do the trick!
