### ISSUE TITLE
Collections based on Jellyseerr user requests?

### ISSUE THREAD

**Issue by Coliinnn** [Schaka/janitorr#8]
Hi, as Janitorr is based heavily on Maintainerr, I am wondering if this application can also create Collections in Jellyfin based on what users requested through Jellyseerr. I see that this is a function in Maintainerr but could not find whether it is or is not supported in Janitorr.

 If not currently, is this 'rule-based matching' something that might be considered for future development?

Thank you!

**Comment by Schaka** [comment]
Collections are incredibly limited in Jellyfin and not at all the same as in Plex.
I'm not quite sure what you're asking for. You would want a collection create on a per-user-basis that automatically contains the media they requested?

It should automatically show up in your existing movies and TV collections already. 
Right now, I'm creating symbolic links to "duplicate" media and toss it into a custom media library. 

If I understand you correctly, what you're asking for may be possible but definitely isn't something I'd be willing to do.

**Comment by Coliinnn** [comment]
Yes, basically I want to have a watchlist for each user. I understand we have the large overall library with all movies/tv, but since people are specifically requesting things that _they themselves_ want to watch via Jellyseerr, I thought it would make sense to group the requests for each person in a watchlist. But I am not sure how to achieve this in Jellyfin, whether it is through playlists, separate libraries (with hardlinks) or collections in Jellyfin. Do I understand that you have a similar system and create new libraries for each user? Is creating those symlinks a manual process for you?

Since in Maintainerr I saw screenshots with rules about creating custom collections based on who requested media, I was hoping that would also be possible in Janitorr (since it is a direct fork of Maintainerr). But I understand that APIs are more limited.

**Comment by Schaka** [comment]
Janitorr is meant for media cleanup. The kind of feature you want would be perfect to request over at Jellyseerr.

This code isn't forked from Maintainerr at all, btw. It's written from scratch without looking at Maintainerr at all. I liked the features and didn't Maintainerr running with Jellyfin and Jellyseerr (not a surprise, they are too different). It's not even the same language - so things aren't easily transferable.

To create collections (which isn't really possible in Jellyfin), I find media in the arrs and on drive, then create a folder and fill it with symlinks to the original files. The only thing you can do via the Jellyfin API is creating media libraries. If you create a movie library and point it towards your folder full of symlinks, this will work and is essentially what I'm doing. These libraries are available to all users.

You can create playlists per user in Jellyfin, but I think the API is only available to the logged in user, so you wouldn't be able to create one per user. It looks like [it might be possible](https://api.jellyfin.org/#tag/Playlists/operation/CreatePlaylist) - but deleting items from Jellyfin also looked like it may be possible until it turned out you needed user auth.

**Comment by Coliinnn** [comment]
I see, thanks for the explanation and my bad for assuming the code was forked directly! In conclusion it seems there is currently not a great way to automate this. Unfortunate, perhaps sometime in the future in the Jellyfin or Jellyseerr project. I will make the suggestion.
