### ISSUE TITLE
Feature request: "run once" mode

### ISSUE THREAD

**Issue by mgabor3141** [Schaka/janitorr#84]
I'd like to run Janitorr as part of my nightly maintenance script, instead of on the default schedule. How can I Have the container do its thing and then exit? Other than starting it and killing it after ~59 minutes or so

**Comment by Schaka** [comment]
This is something that can be implemented. But I don't know when I'll get to it. Spring applications in the way this one is written don't really serve as a script. 
Are you seeing too much resource overhead even with the native image? I have not once seen that exceed 120mb ram or so. 


You'd otherwise have to start and kill it after reaction to a log message you expect.

The initial run is already done on startup.

**Comment by mgabor3141** [comment]
Thank you for all your work on this project, and the prompt response.

I think the resources it uses is perfectly okay, the reason I decided to do my daily maintenance this way is to limit avoidable disk spinups to pre-determined time window.

**Comment by Schaka** [comment]
This is now available in the latest develop image.
You can consult the changed template here:

https://github.com/Schaka/janitorr/blob/develop/src/main/resources/application-template.yml
